import { RichText } from '../../src/EdNotes.RichText/wwwroot/editor/ednotes.richtext.bundle.js';
import EdNotesRichText from '../../src/EdNotes.RichText/wwwroot/editor/ednotes.richtext.api.js';

function collapseAt(node, offset){
  const sel=document.getSelection(); const r=document.createRange();
  r.setStart(node, Math.min(offset, node.length||0)); r.collapse(true);
  sel.removeAllRanges(); sel.addRange(r);
}
function selectRange(node,start,end){ const sel=document.getSelection(); const r=document.createRange(); r.setStart(node,start); r.setEnd(node, Math.min(end,node.length||0)); if(r.collapsed){ r.setEnd(node, Math.min(start+1, node.length||0)); } sel.removeAllRanges(); sel.addRange(r);} 
function notifySelection(){ document.dispatchEvent(new Event('selectionchange')); }
function clickToolbarButton(ed, name){ ed.root.querySelector(`button[data-plugin="${name}"]`).click(); }
function chooseToolbarOption(ed, value){ const select=ed.root.querySelector('select.rtx-select'); select.value=value; select.dispatchEvent(new Event('change', { bubbles:true })); }

describe('command coverage (light)', ()=>{
  function create(){ document.body.innerHTML=''; const ta=document.createElement('textarea'); ta.id='tx'; ta.value='<p>Hello world</p>'; document.body.appendChild(ta); RichText.attach('#tx',{ promptLink: ()=>'https://example.com' }); return RichText._all().slice(-1)[0]; }
  test('toolbar renders styled buttons, dropdown controls, and hover tooltips', ()=>{ document.body.innerHTML=''; const ta=document.createElement('textarea'); ta.id='tx'; ta.value='<p>Hello world</p>'; document.body.appendChild(ta); const ed=EdNotesRichText.init({ selector:'#tx', promptLink: ()=>'https://example.com' })[0]; const toolbar=ed.root.querySelector('.rtx-toolbar'); const buttons=[...toolbar.querySelectorAll('button.rtx-button')]; const select=toolbar.querySelector('select.rtx-select'); expect(toolbar).toBeTruthy(); expect(buttons.length).toBeGreaterThan(0); expect(buttons.every(button=> button.title === button.getAttribute('aria-label') && button.title.length > 0)).toBe(true); expect(select).toBeTruthy(); expect(select.title).toBe(select.getAttribute('aria-label')); expect(select.title.length).toBeGreaterThan(0); });
  test('toolbar inline formatting, undo redo, and clear formatting work through the UI', ()=>{ document.body.innerHTML=''; const ta=document.createElement('textarea'); ta.id='tx'; ta.value='<p>Hello world</p>'; document.body.appendChild(ta); const ed=EdNotesRichText.init({ selector:'#tx' })[0]; let paragraph=ed.content.querySelector('p'); selectRange(paragraph.firstChild,0,5); notifySelection(); clickToolbarButton(ed,'bold'); expect(ed.content.querySelector('strong')).toBeTruthy(); clickToolbarButton(ed,'undo'); expect(ed.content.querySelector('strong')).toBeFalsy(); clickToolbarButton(ed,'redo'); expect(ed.content.querySelector('strong')).toBeTruthy(); ed.setHTML('<p>Hello world</p>'); paragraph=ed.content.querySelector('p'); selectRange(paragraph.firstChild,0,5); notifySelection(); clickToolbarButton(ed,'italic'); expect(ed.content.querySelector('em')).toBeTruthy(); ed.setHTML('<p>Hello world</p>'); paragraph=ed.content.querySelector('p'); selectRange(paragraph.firstChild,0,5); notifySelection(); clickToolbarButton(ed,'underline'); expect(ed.content.querySelector('u')).toBeTruthy(); ed.setHTML('<p>Hello world</p>'); paragraph=ed.content.querySelector('p'); selectRange(paragraph.firstChild,0,5); notifySelection(); clickToolbarButton(ed,'bold'); const strong=ed.content.querySelector('strong'); selectRange(strong.firstChild,0,5); notifySelection(); clickToolbarButton(ed,'removeformat'); expect(ed.content.querySelector('strong')).toBeFalsy(); });
  test('toolbar block, list, task, table, link, unlink, and math controls work through the UI', ()=>{ document.body.innerHTML=''; const ta=document.createElement('textarea'); ta.id='tx'; ta.value='<p>Hello world</p>'; document.body.appendChild(ta); const ed=EdNotesRichText.init({ selector:'#tx', promptLink: ()=>'https://example.com', promptMath: ()=>'x^2' })[0]; let paragraph=ed.content.querySelector('p'); selectRange(paragraph.firstChild,0,5); notifySelection(); chooseToolbarOption(ed,'block:h2'); expect(ed.content.querySelector('h2')).toBeTruthy(); ed.setHTML('<p>List item</p>'); paragraph=ed.content.querySelector('p'); selectRange(paragraph.firstChild,0,9); notifySelection(); clickToolbarButton(ed,'bullist'); expect(ed.content.querySelector('ul li')).toBeTruthy(); ed.setHTML('<p>List item</p>'); paragraph=ed.content.querySelector('p'); selectRange(paragraph.firstChild,0,9); notifySelection(); clickToolbarButton(ed,'numlist'); expect(ed.content.querySelector('ol li')).toBeTruthy(); ed.setHTML('<p>Task item</p>'); paragraph=ed.content.querySelector('p'); collapseAt(paragraph.firstChild,0); notifySelection(); clickToolbarButton(ed,'task'); expect(ed.content.querySelector('ul[data-list="task"] li')).toBeTruthy(); ed.setHTML('<p>Table</p>'); paragraph=ed.content.querySelector('p'); collapseAt(paragraph.firstChild,0); notifySelection(); clickToolbarButton(ed,'table'); expect(ed.content.querySelector('table')).toBeTruthy(); ed.setHTML('<p>Hello world</p>'); paragraph=ed.content.querySelector('p'); collapseAt(paragraph.firstChild,5); notifySelection(); document.getSelection().removeAllRanges(); clickToolbarButton(ed,'link'); const link=ed.content.querySelector('a'); expect(link).toBeTruthy(); expect(link.getAttribute('href')).toBe('https://example.com'); collapseAt(link.firstChild,0); notifySelection(); clickToolbarButton(ed,'unlink'); expect(ed.content.querySelector('a')).toBeFalsy(); ed.setHTML('<p>Eq </p>'); paragraph=ed.content.querySelector('p'); collapseAt(paragraph.firstChild,3); notifySelection(); document.getSelection().removeAllRanges(); clickToolbarButton(ed,'math'); const math=ed.content.querySelector('.math'); expect(math).toBeTruthy(); expect(math.textContent).toContain('x^2'); });
  test('toolbar link and math controls restore the saved selection across prompts', ()=>{ document.body.innerHTML=''; const ta=document.createElement('textarea'); ta.id='tx'; ta.value='<p>Hello world</p>'; document.body.appendChild(ta); const ed=EdNotesRichText.init({ selector:'#tx', promptLink: ()=>'https://example.com', promptMath: ()=>'x^2' })[0]; const paragraph=ed.content.querySelector('p'); collapseAt(paragraph.firstChild,5); document.dispatchEvent(new Event('selectionchange')); document.getSelection().removeAllRanges(); ed.root.querySelector('button[data-plugin="link"]').click(); const link=ed.content.querySelector('a'); expect(link).toBeTruthy(); expect(link.getAttribute('href')).toBe('https://example.com'); ed.setHTML('<p>Eq </p>'); const mathParagraph=ed.content.querySelector('p'); collapseAt(mathParagraph.firstChild,3); document.dispatchEvent(new Event('selectionchange')); document.getSelection().removeAllRanges(); ed.root.querySelector('button[data-plugin="math"]').click(); const math=ed.content.querySelector('.math'); expect(math).toBeTruthy(); expect(math.textContent).toContain('x^2'); });
  test('link add/remove', ()=>{ const ed=create(); const p=ed.content.querySelector('p'); collapseAt(p.firstChild,5); ed.bus.exec('link:add'); expect(ed.content.querySelector('a')).toBeTruthy(); collapseAt(ed.content.querySelector('a').firstChild,0); ed.bus.exec('link:remove'); expect(ed.content.querySelector('a')).toBeFalsy(); });
  test('block h2 then no-op second time', ()=>{ const ed=create(); const p=ed.content.querySelector('p'); expect(p).toBeTruthy(); expect(p.firstChild.nodeType).toBe(3); selectRange(p.firstChild,0,5); ed.bus.exec('block:h2'); const h2=ed.content.querySelector('h2'); expect(h2).toBeTruthy(); const before=h2.outerHTML; selectRange(h2.firstChild,0,1); ed.bus.exec('block:h2'); expect(h2.outerHTML).toBe(before); });
  test('list:ul toggle', ()=>{ const ed=create(); const p=ed.content.querySelector('p'); selectRange(p.firstChild,0,5); ed.bus.exec('list:ul'); expect(ed.content.querySelector('ul li')).toBeTruthy(); const liText=ed.content.querySelector('ul li').firstChild; selectRange(liText,0,liText.length||0); ed.bus.exec('list:ul'); expect(ed.content.querySelectorAll('p').length).toBeGreaterThan(0); });
  test('task list create + toggle off', ()=>{ const ed=create(); const p=ed.content.querySelector('p'); collapseAt(p.firstChild,0); ed.bus.exec('list:task'); expect(ed.content.querySelector('ul[data-list="task"]')).toBeTruthy(); collapseAt(ed.content.querySelector('ul[data-list="task"]').querySelector('li').firstChild,0); ed.bus.exec('list:task'); expect(ed.content.querySelector('ul[data-list="task"]')).toBeFalsy(); });
});